apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-api
  namespace: demo
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: demo-api
  endpoints:
    - port: http
      path: /metrics
      interval: 3s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-api
  namespace: demo
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend-api
  endpoints:
    - port: http
      path: /metrics
      interval: 3s
